### ISSUE TITLE
Reuse target?

### ISSUE THREAD

**Issue by badtant** [smooth-code/react-teleporter#11]
Hi, so I have the code below. A create a teleporter and set up it's target. Then renderAComponent will have a switch that renders different components based on some props.

The first component (A) that renders and imports FooterTeleport and defines a <FooterTeleport.Source> works nice but then on an update a different component (B) renders and replaces (A) and also uses <FooterTeleport.Source> nothing shows up in the target.

Is this a bug or am I doing something wrong?

```
export const FooterTeleport = createTeleporter();

<>
{renderAComponent()}
<div className={styles.flexFooter}>
<FooterTeleport.Target />
</div>
</>
```

**Comment by gregberge** [comment]
It must be a bug, could you provide a repro repository?

**Comment by badtant** [comment]
Sure, here is a Sandbox.
https://codesandbox.io/s/mxx30

When clicking on the button to change page to page2 there is nothing rendered into the teleporter target.
