### ISSUE TITLE
Prevent double usage

### ISSUE THREAD

**Issue by theKashey** [smooth-code/react-teleporter#2]
- [ ] API should have protection from more than one active `Source`, and more than one active `Target` (longer that useEffect)
- [x] it should properly handle `Target` and `Source` remount
- [x] it should stand `Target` unmount (probably would fail right now)
- [ ] `Source`  should have an option to enforce `Target` existence (enabled by default)

**Comment by gregberge** [comment]
> Source should have an option to enforce Target existence (enabled by default)

This point is not relevant for me, we do have support for it.

**Comment by gregberge** [comment]
For now I will keep it simple, I covered it with tests that explain the current behaviour:

- If you provide multiple sources, they end-up in the same target
- The latest target defined win
