### ISSUE TITLE
multiple teleporters, factory for teleporters

### ISSUE THREAD

**Issue by aappddeevv** [smooth-code/react-teleporter#21]
I have a page that has 4 sections in it. Each section has a header and some content. I would like to have teleporters for each section on the page so that their children can teleport headers into the header section area. Each section is the same component instantiated with different "titles." It's also possible that the same child, with different props, will be on the same page multiple times.

Is this possible?

It looks like each call to `createTeleporter` creates a unique instance.

I was thinking that each Target and Source (from a single createTeleporter call) could be position in the tree and when a source is laid into the react tree, it climbs the tree looking for the nearest Target partner. It's not clear that this is the right model.

Is there way to support my scenario or is that not the intent?

There is a way around this of course which is to define and create a teleporter for every parent-child pair that may occur. Perhaps then I don't need a teleporter then just some functions since I'm in the same tree.

**Comment by gregberge** [comment]
Hello @aappddeevv, your scenario is not clear for me. Te code of this library is simple and will stick to simple use cases. If you need more complex behaviour, then you will have to create a custom solution.
