### ISSUE TITLE
Example test cases that don't render the Target component

### ISSUE THREAD

**Issue by tobiasbueschel** [smooth-code/react-teleporter#27]
Hi @gregberge 👋 

Thanks a lot for your work on this library! I've gone through the [test cases](https://github.com/gregberge/react-teleporter/blob/master/src/index.test.js), but I'm not clear on what approach you would recommend to test a component that renders a `source` teleporter but doesn't include the `target` itself.

**For example:**

```js
// Assume we have a component that exports => HeaderSource
import HeaderSource from 'components/HeaderSource'

function SomePage() {
  return (
    <main>
      <HeaderSource>Foo Bar</HeaderSource>
      <section>
        lorem ipsum
      </section>
    </main>
```

How would you go about testing that the component renders correctly with the correct title?

```js
it('should render correct title', () => {
  render(<SomePage />)
  expect(screen.getByText('Foo Bar')).toBeInTheDocument() // fails as HeaderSource doesn't render correctly in JSDOM
});
```

**Comment by gregberge** [comment]
Hi @tobiasbueschel, If you want to test it, you should add a Target component in the test and test that it contains the element.
