### ISSUE TITLE
Suggestion for multiple layouts for frontend and admin 

### ISSUE THREAD

**Issue by aaronamm** [smooth-code/react-teleporter#30]
Hello @gregberge 

I like your project a lot and it is very helpful.

I need to create a single page app that work both frontend and backend.
Therefore, I have used react-teleporter to solve my problem and it works great. 

However, I am not sure if my approach is correct with integrate react-teleporter with multiple layouts.
Here is my current implementation now.

Frontend is a layout component, used in App.tsx
https://github.com/codesanook/Codesanook.Examples/blob/master/codesanook-examples-debug-create-react-app/src/App.tsx#L40

Frontend has react-teleporter target for inject a title.
https://github.com/codesanook/Codesanook.Examples/blob/master/codesanook-examples-debug-create-react-app/src/pages/frontend/Frontend.tsx#L31

And source is from Home.tsx which is a actual page component
https://github.com/codesanook/Codesanook.Examples/blob/master/codesanook-examples-debug-create-react-app/src/pages/frontend/Home.tsx#L7

If it is possible, could you please give me some suggestion or other approach of multiple layouts implementation.
Thanks.

**Comment by gregberge** [comment]
Hello @aaronamm, something hit me:

> I need to create a single page app that work both frontend and backend.

Are you aware that react-teleporter is not compatible with SSR?

About your implementation, react-teleporter is pretty simple to use, your implemention looks good to me.

**Comment by aaronamm** [comment]
@gregberge  Thanks for confirming me that my implementation is okay.
Infect, I don't want to use server-side rending, just single page app that support both frontend and admin UI.

I have this question because most of my experiences are about ASP.NET Core MVC and Java web development.
These frameworks make separated layout for frontend and admin UI and look obvious.
This makes me think if I do it right when working with React Router.

FYI, your react-teleporter makes me feel like a home because its usage is the same as defining a section in ASP.NET Core MVC
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-5.0#sections

Thanks for making a good library.
