### ISSUE TITLE
React 18 type error

### ISSUE THREAD

**Issue by bartels** [smooth-code/react-teleporter#40]
React 18 is out. I'm getting some type errors, but react-teleporter is otherwise working for me.

Type errors are  is when using `Component.Source`, likely due to removal of implicit children in the new types, explained here:  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

```tsx
const Component = createTeleporter()

<Component.Source>
  <p>test with element</p>
</Component.Source>
```

`error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.`

```tsx
<Component.Source>
  test with string
</Component.Source>
```
`error TS2559: Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes'.`

I think updating `TeleporterType['Source']` to explicitly add children (`children?: React.ReactNode`) would likely fix.

**Comment by gregberge** [comment]
Fixed in 16ea2f1
