### ISSUE TITLE
Portal Video components, and automatically transition to the playing state

### ISSUE THREAD

**Issue by Adxiong** [smooth-code/react-teleporter#41]
## 🚀 Feature Proposal
When I put a video in the source, click the button and send it to the target, so that the video playback status in the targte will automatically continue to that in the source, so as to achieve universality, such as video or source Element

**Comment by gregberge** [comment]
Hi @Adxiong, it is an edgecase, I suggest you to fork the code for your own use case. I prefer to keep it light instead of supporting that kind of use cases.
