### ISSUE TITLE
[Question] The context problem

### ISSUE THREAD

**Issue by lkostrowski** [smooth-code/react-teleporter#6]
Hi

I recently faced the problem I explained here

https://stackoverflow.com/questions/56393510/pass-unknown-context-to-children-component

Does it actually solve it? tldr - does it pass context from target parent to source?

**Comment by gregberge** [comment]
Yes it does. It uses React.createPortal under the hood, so the context works. But the context pass from the source to the target. If you want the inverse. You could just use a context, set children and render them in a target. You don’t need this library.
