### ISSUE TITLE
Placeholder component

### ISSUE THREAD

**Issue by IniZio** [smooth-code/react-teleporter#8]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

Add a Placeholder component which serves as default value when no Source is present.

Example implementation: https://gist.github.com/IniZio/68872edc1acf2ecfadf5ffffa06f321a

## Motivation

Please outline the motivation for the proposal.

Provider a default value to Target

## Example

Please provide an example for how this feature would be used.

```jsx
const Header = createTeleporter()

<Header.Target/>

<Header.Placeholder>This is placeholder</<Header.Placeholder>

// This is placeholder
```

```jsx
const Header = createTeleporter()

<Header.Target/>

<Header.Placeholder>This is placeholder</<Header.Placeholder>

<Header.Source>Source 1</<Header.Source>

// Source 1
```

## Pitch

Why does this feature belong in the xstyled ecosystem?

**Comment by gregberge** [comment]
Hello @IniZio, thanks for the suggestion!

What do you think about this API:

```js
<Header.Target fallback="This is placeholder" />
```

**Comment by IniZio** [comment]
I referred to https://github.com/javivelasco/react-tunnels so came up with this way.

I did think of your suggested way too, but i think Placeholder way allows placeholder to be overridden?

**Comment by gregberge** [comment]
In fact I don't get the difference between Source and Placeholder with your example. Ah several sources are merged.. I see. I think, I should change the way it works and use only the latest source defined. What do you think?

**Comment by IniZio** [comment]
The react-tunnels lib allow toggling `multiple` so that the teleported content will either concat each other or replace other.

Currently react-teleporter `Source` just concats each other, but I think replace is actually the more common use case

**Comment by gregberge** [comment]
#12 solves it.
